"""Zero-shot label vocabulary. Each entry: tag -> natural-language description for the text tower."""

# What *kind* of image it is (exactly one is chosen).
KINDS = {
    "photo": "a photograph taken with a camera",
    "screenshot": "a screenshot of a computer or phone screen",
    "document": "a scanned document or a page of printed text",
    "receipt": "a shopping receipt, invoice or bill",
    "illustration": "a drawing, illustration or digital art",
    "chart": "a chart, graph or diagram",
    "meme": "an internet meme with caption text",
}

# What is *in* it (multi-label; every tag above the threshold is kept).
TAGS = {
    # people
    "people": "people",
    "selfie": "a selfie",
    "group": "a group of friends",
    "portrait": "a portrait of a person",
    "baby": "a baby",
    "kids": "children playing",
    # animals
    "dog": "a dog",
    "cat": "a cat",
    "bird": "a bird",
    "horse": "a horse",
    "fish": "fish",
    "insect": "an insect",
    "wildlife": "wild animals",
    # food & drink
    "food": "food",
    "meal": "a plated meal",
    "dessert": "a dessert",
    "coffee": "a cup of coffee",
    "drinks": "drinks",
    "fruit": "fruit",
    "pizza": "pizza",
    "cake": "a cake",
    # vehicles
    "car": "a car",
    "motorcycle": "a motorcycle",
    "bicycle": "a bicycle",
    "airplane": "an airplane",
    "train": "a train",
    "boat": "a boat",
    # nature & outdoors
    "beach": "a beach",
    "ocean": "the ocean",
    "mountains": "mountains",
    "forest": "a forest",
    "lake": "a lake",
    "river": "a river",
    "waterfall": "a waterfall",
    "desert": "a desert",
    "snow": "snow",
    "sunset": "a sunset",
    "sunrise": "a sunrise",
    "night": "a night scene",
    "sky": "the sky and clouds",
    "stars": "a starry night sky",
    "flowers": "flowers",
    "garden": "a garden",
    "park": "a park",
    "trees": "trees",
    "plants": "plants",
    # places
    "city": "a city skyline",
    "street": "a street",
    "building": "a building",
    "architecture": "architecture",
    "home": "the inside of a home",
    "kitchen": "a kitchen",
    "bedroom": "a bedroom",
    "office": "an office",
    "classroom": "a classroom",
    "restaurant": "a restaurant",
    "cafe": "a cafe",
    "shop": "a shop",
    "museum": "a museum",
    "temple": "a temple",
    "church": "a church",
    "landmark": "a famous landmark",
    "stadium": "a stadium",
    "airport": "an airport",
    "road": "a road",
    # events & activities
    "party": "a party",
    "wedding": "a wedding",
    "birthday": "a birthday celebration",
    "concert": "a concert",
    "festival": "a festival",
    "graduation": "a graduation ceremony",
    "christmas": "christmas decorations",
    "fireworks": "fireworks",
    "sports": "people playing sports",
    "football": "football",
    "cricket": "cricket",
    "basketball": "basketball",
    "gym": "a gym workout",
    "hiking": "hiking",
    "travel": "travel and sightseeing",
    "swimming": "swimming",
    # objects & text
    "whiteboard": "a whiteboard with writing",
    "handwriting": "handwritten notes",
    "book": "a book",
    "laptop": "a laptop",
    "phone": "a smartphone",
    "code": "computer code",
    "slides": "a presentation slide",
    "spreadsheet": "a spreadsheet",
    "map": "a map",
    "ticket": "a ticket",
    "id card": "an identity card",
    "certificate": "a certificate",
    "menu": "a restaurant menu",
    "poster": "a poster",
    "sign": "a sign",
    "logo": "a logo",
    "qr code": "a qr code",
    "clothes": "clothes",
    "shoes": "shoes",
    "jewelry": "jewelry",
    "toys": "toys",
    "video game": "a video game",
    "anime": "anime",
    "cartoon": "a cartoon",
    "art": "a painting or artwork",
    "shapes": "abstract geometric shapes",
    "pattern": "a repeating pattern",
    "furniture": "furniture",
    # colours (cheap but useful for queries like "the red one")
    "red": "something red",
    "blue": "something blue",
    "green": "something green",
    "yellow": "something yellow",
    "orange": "something orange",
    "purple": "something purple",
    "pink": "something pink",
    "black and white": "a black and white image",
}
